# Generated by Django 3.1.4 on 2021-01-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('temp', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('visibility', models.IntegerField()),
                ('dew_point_tmp', models.FloatField()),
                ('solar_rad', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('snowfall', models.FloatField()),
                ('season', models.CharField(choices=[('Winter', 'Winter'), ('Autumn', 'Autumn'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=6)),
                ('holiday', models.CharField(choices=[('Holiday', 'Holiday'), ('No Holiday', 'No Holiday')], max_length=10)),
                ('func_day', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
    ]
