# Generated by Django 3.1.4 on 2021-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='func_day',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Autumn', 'Autumn'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=10),
        ),
    ]
