# Generated by Django 3.1.4 on 2021-01-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20210103_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='func_day',
            field=models.CharField(choices=[('Yes', 1), ('No', 0)], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='holiday',
            field=models.CharField(choices=[('Holiday', 1), ('No Holiday', 0)], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='season',
            field=models.CharField(choices=[('Winter', 0), ('Autumn', 1), ('Summer', 2), ('Spring', 3)], max_length=10),
        ),
    ]
