# Generated by Django 3.1.4 on 2021-01-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20210104_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='season',
            field=models.CharField(choices=[(0, 'Winter'), ('Autumn', 1), ('Summer', 2), ('Spring', 3)], max_length=10),
        ),
    ]
