# Generated by Django 3.1.4 on 2021-01-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20210104_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='func_day',
            field=models.CharField(choices=[(1, 'Yes'), (0, 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='holiday',
            field=models.CharField(choices=[(1, 'Holiday'), (0, 'No Holiday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='season',
            field=models.CharField(choices=[(0, 'Winter'), (1, 'Autumn'), (2, 'Summer'), (3, 'Spring')], max_length=10),
        ),
    ]
