# Generated by Django 3.1.4 on 2021-01-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_auto_20210104_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='holiday',
            field=models.CharField(choices=[('Holiday', 'Holiday'), ('Holiday', 'No Holiday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bike',
            name='season',
            field=models.CharField(choices=[('Winter', 'Winter'), ('Autumn', 'Autumn'), ('Summer', 'Summer'), ('Spring', 'Spring')], max_length=10),
        ),
    ]
